### PR TITLE
Modules implementation

### PR DESCRIPTION
**Pull request by mariobarrioss**
The project was separated into modules and webpack was used as a bundler.

* Added page-load.js, menu.js, contact.js, and used index.js as the entry point for webpack build.
* Each tab in the main page corresponds to a module that renders the content dynamically.
* Added event listeners to handle tab switching logic.

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @mariobarrioss   👨‍🚀 
### Very good job so far.

However, there are some changes that need to be implemented in order to meet the project requirements.  👨‍💻  ⬇️ 
Please check out below.

****
- [x] Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
Kindly add a brief description about what you did on this project, e.g. A list with the main features of the project.
****
- [x] Comments: It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)). 
There is a couple of comments in page-load.js and menu.js, please remove them.
****

### **Please make the changes required and submit for re-review once you are ready!** 

****

### Status: Changes required. ♻️  
****

Happy coding!  💻  
Have a great day 🙂

If you need more clarifications kindly reach me on slack.
**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

**Comment by mariobarrioss** [comment]
@davomartinez-dev Thank you for your prompt review. I edited the Pull Request title and comment as requested, and also removed commented code.

**Review by MarioDena — APPROVED** [review]
Hello Man! Great work on your project. 🎖️ 

The project is approved but before you merge please make the following change to your README.

- [ ] This project is not built using Vanilla JS as stated on your readme, You are using a modern superset known as E6S. Please correct that.


Cheers!!  👍

**Comment by mariobarrioss** [comment]
@MarioDena Thanks for the review. The suggested change was implemented.

**Pull request merged**
